packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.45.30
  "@platforma-sdk/ui-vue": ^1.45.31
  "@platforma-sdk/workflow-tengo": ^5.6.1
  "@platforma-sdk/block-tools": ^2.6.21
  "@platforma-sdk/test": ^1.45.33
  "@platforma-sdk/tengo-builder": ^2.3.9
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/eslint-config": ^1.1.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  "vue": ^3.5.15
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "turbo": ^2.5.4

  "vite": ^6.3.5
  "vitest": ~2.1.9
  "@vitejs/plugin-vue": ^5.2.4
  "vite-plugin-dts": ^4.3.0

  "@changesets/cli": ^2.29.5
  "js-yaml": "^4.1.0"
